title: Genome 373 (Spring 2019)
author: Sarah Hilton
email: skhilton@uw.edu
description: > # this means to ignore newlines until "show_exerpts:"
  Material for Genome 373 quiz section
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- slides.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
